const fs = require('fs');

const fileOut = 'jeweltrack_full_database_setup.txt';

let sql = "-- =========================================================================\n" +
"-- JEWELTRACK COMPREHENSIVE ORACLE DATABASE SETUP SCRIPT\n" +
"-- =========================================================================\n" +
"-- INSTRUCTIONS:\n" +
"-- 1. Run the USER CREATION segment as SYSDBA (e.g., ADMIN user).\n" +
"-- 2. Connect as JEWELTRACK_APP and run the rest of the script.\n" +
"--\n" +
"-- This file contains:\n" +
"-- - User/Schema Creation\n" +
"-- - Table definitions\n" +
"-- - Minimum 50 records per table\n" +
"-- - Analytical Views\n" +
"-- =========================================================================\n\n" +
"-- ==========================================\n" +
"-- 1. USER CREATION (Run as SYSDBA)\n" +
"-- ==========================================\n" +
"-- DROP USER JEWELTRACK_APP CASCADE;\n" +
"CREATE USER JEWELTRACK_APP IDENTIFIED BY YourSecurePassword123;\n" +
"GRANT CONNECT, RESOURCE, CREATE VIEW TO JEWELTRACK_APP;\n" +
"ALTER USER JEWELTRACK_APP QUOTA UNLIMITED ON USERS;\n\n" +
"-- Connect to JEWELTRACK_APP before running the following:\n\n" +
"-- ==========================================\n" +
"-- 2. TABLE CREATION\n" +
"-- ==========================================\n\n" +
"CREATE TABLE CUSTOMER (\n" +
"    CustomerId VARCHAR2(20) PRIMARY KEY,\n" +
"    CustomerName VARCHAR2(100) NOT NULL,\n" +
"    Phone VARCHAR2(20) UNIQUE NOT NULL,\n" +
"    Email VARCHAR2(100),\n" +
"    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP\n);\n\n" +
"CREATE TABLE EMPLOYEE (\n" +
"    EmployeeId VARCHAR2(20) PRIMARY KEY,\n" +
"    FirstName VARCHAR2(50) NOT NULL,\n" +
"    LastName VARCHAR2(50) NOT NULL,\n" +
"    Role VARCHAR2(20) CHECK (Role IN ('Admin', 'Staff')),\n" +
"    Email VARCHAR2(100) UNIQUE NOT NULL,\n" +
"    PasswordHash VARCHAR2(255) NOT NULL,\n" +
"    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP\n);\n\n" +
"CREATE TABLE CATEGORY (\n" +
"    CategoryId VARCHAR2(20) PRIMARY KEY,\n" +
"    CategoryName VARCHAR2(50) UNIQUE NOT NULL,\n" +
"    Description VARCHAR2(255)\n);\n\n" +
"CREATE TABLE SUPPLIER (\n" +
"    SupplierId VARCHAR2(20) PRIMARY KEY,\n" +
"    SupplierName VARCHAR2(100) NOT NULL,\n" +
"    ContactPerson VARCHAR2(100),\n" +
"    Phone VARCHAR2(20),\n" +
"    Email VARCHAR2(100),\n" +
"    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP\n);\n\n" +
"CREATE TABLE ITEM (\n" +
"    ItemId VARCHAR2(20) PRIMARY KEY,\n" +
"    ItemName VARCHAR2(100) NOT NULL,\n" +
"    CategoryId VARCHAR2(20) REFERENCES CATEGORY(CategoryId),\n" +
"    SupplierId VARCHAR2(20) REFERENCES SUPPLIER(SupplierId),\n" +
"    Material VARCHAR2(50),\n" +
"    Weight NUMBER(10,2),\n" +
"    BasePrice NUMBER(12,2) NOT NULL,\n" +
"    CurrentStock NUMBER(10) DEFAULT 0 CHECK (CurrentStock >= 0),\n" +
"    ReorderLevel NUMBER(10) DEFAULT 5,\n" +
"    Description VARCHAR2(500),\n" +
"    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP\n);\n\n" +
"CREATE TABLE BILL (\n" +
"    BillId VARCHAR2(20) PRIMARY KEY,\n" +
"    CustomerId VARCHAR2(20) REFERENCES CUSTOMER(CustomerId),\n" +
"    EmployeeId VARCHAR2(20) REFERENCES EMPLOYEE(EmployeeId),\n" +
"    BillDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\n" +
"    TotalAmount NUMBER(12,2) NOT NULL,\n" +
"    DiscountAmount NUMBER(12,2) DEFAULT 0,\n" +
"    TaxAmount NUMBER(12,2) DEFAULT 0,\n" +
"    PaymentMethod VARCHAR2(50)\n);\n\n" +
"CREATE TABLE BILL_ITEM (\n" +
"    BillItemId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n" +
"    BillId VARCHAR2(20) REFERENCES BILL(BillId) ON DELETE CASCADE,\n" +
"    ItemId VARCHAR2(20) REFERENCES ITEM(ItemId),\n" +
"    Quantity NUMBER(10) NOT NULL CHECK (Quantity > 0),\n" +
"    UnitPrice NUMBER(12,2) NOT NULL,\n" +
"    TotalPrice NUMBER(12,2) AS (Quantity * UnitPrice)\n);\n\n" +
"CREATE TABLE PURCHASE (\n" +
"    PurchaseId VARCHAR2(20) PRIMARY KEY,\n" +
"    SupplierId VARCHAR2(20) REFERENCES SUPPLIER(SupplierId),\n" +
"    PurchaseDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\n" +
"    TotalAmount NUMBER(12,2) NOT NULL,\n" +
"    Status VARCHAR2(20) DEFAULT 'Completed',\n" +
"    PaymentMethod VARCHAR2(50)\n);\n\n" +
"CREATE TABLE PURCHASE_ITEM (\n" +
"    PurchaseItemId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n" +
"    PurchaseId VARCHAR2(20) REFERENCES PURCHASE(PurchaseId) ON DELETE CASCADE,\n" +
"    ItemId VARCHAR2(20) REFERENCES ITEM(ItemId),\n" +
"    Quantity NUMBER(10) NOT NULL CHECK (Quantity > 0),\n" +
"    UnitCost NUMBER(12,2) NOT NULL,\n" +
"    TotalCost NUMBER(12,2) AS (Quantity * UnitCost)\n);\n\n" +
"-- ==========================================\n" +
"-- 3. DATA INSERTION (Min 50 rows per table)\n" +
"-- ==========================================\n\n";

const fnames = ["Aarav","Vivaan","Aditya","Vihaan","Arjun","Sai","Reynansh","Ayaan","Krishna","Ishaan","Shaurya","Atharva","Pranav","Rishi","Sandhya","Priya","Neha","Anjali","Meera","Isha","Riya","Kavya","Sneha","Pooja","Divya","Kriti","Nidhi","Shikha","Gaurav","Vikram","Rajesh","Suresh","Ramesh","Mohit","Rohit","Rahul","Amit","Sumit","Anil","Sunil","Raj","Deepak","Sanjay","Ajay","Vijay","Pankaj","Manoj","Santosh","Ashok","Ram"];
const lnames = ["Sharma","Patel","Singh","Kumar","Reddy","Iyer","Gupta","Deshmukh","Joshi","Kaur","Rao","Nair","Menon","Das","Bose","Choudhury","Sen","Varma","Kapoor","Malhotra","Chopra","Soni","Goel","Bansal","Agarwal","Mittal","Jain","Shah","Mehta","Desai","Parekh","Banerjee","Mukherjee","Chatterjee","Bhattacharya","Mahajan","Dubey","Tiwari","Mishra","Pandey","Shukla","Dixit","Yadav","Thakur","Nath","Sinha","Yong","Fernandes","D'Souza","Venkatesh"];

function randItem(arr) { return arr[Math.floor(Math.random() * arr.length)]; }
function randInt(min, max) { return Math.floor(Math.random() * (max - min + 1)) + min; }
function randPhone() { return '9' + String(Math.floor(Math.random() * 900000000) + 100000000); }

// 1. CUSTOMERS (50)
sql += "-- CUSTOMER TABLE\n";
const customerIds = [];
for (let i=1; i<=50; i++) {
    let id = 'CUST-' + (10000 + i);
    let name = randItem(fnames) + ' ' + randItem(lnames);
    let phone = randPhone();
    let email = name.toLowerCase().replace(' ', '.') + i + '@email.com';
    customerIds.push(id);
    sql += "INSERT INTO CUSTOMER (CustomerId, CustomerName, Phone, Email) VALUES ('" + id + "', '" + name + "', '" + phone + "', '" + email + "');\n";
}

// 2. EMPLOYEES (50)
sql += "\n-- EMPLOYEE TABLE\n";
const employeeIds = [];
for (let i=1; i<=50; i++) {
    let id = 'EMP-' + (500 + i);
    let fname = randItem(fnames);
    let lname = randItem(lnames);
    let role = i <= 5 ? 'Admin' : 'Staff';
    let email = fname.toLowerCase() + '.e' + i + '@jeweltrack.com';
    employeeIds.push(id);
    sql += "INSERT INTO EMPLOYEE (EmployeeId, FirstName, LastName, Role, Email, PasswordHash) VALUES ('" + id + "', '" + fname + "', '" + lname + "', '" + role + "', '" + email + "', 'hash123');\n";
}

// 3. CATEGORY (50)
sql += "\n-- CATEGORY TABLE\n";
const categoryIds = [];
const catNames = [
  "Gold Necklace","Diamond Ring","Silver Bangle","Platinum Chain","Gemstone Pendant","Ruby Earring","Sapphire Bracelet","Emerald Choker","Bridal Set","Anklet Pair",
  "Rose Gold Ring","Antique Bangle","Temple Pendant","Kundan Set","Polki Earring","Solitaire Studs","Mens Bracelet","Gold Cufflinks","Pearl String","Navratna Ring",
  "Silver Toe Ring","White Gold Band","Tennis Bracelet","Mangalsutra","Maang Tikka","Jhumka","Chandbali","Nath","Armlet","WaistBelt",
  "Gold Coin 1g","Gold Coin 5g","Silver Coin 10g","Platinum Band","Baby Bangle","Initial Pendant","Locket","Charm Bracelet","Hoop Earring","Drop Earring",
  "Chandelier Earring","Cocktail Ring","Stackable Ring","Eternity Band","Promise Ring","Religious Pendant","Signet Ring","Chain Necklace","Choker Necklace","Pendant Necklace"
];
for (let i=0; i<50; i++) {
    let id = 'CAT-' + (100 + i);
    let cname = catNames[i % catNames.length] + (i >= catNames.length ? ' V2' : '');
    categoryIds.push(id);
    sql += "INSERT INTO CATEGORY (CategoryId, CategoryName, Description) VALUES ('" + id + "', '" + cname + "', 'All " + cname + " variations');\n";
}

// 4. SUPPLIER (50)
sql += "\n-- SUPPLIER TABLE\n";
const supplierIds = [];
const supWords = ["Jewellers","Wholesale","Traders","Gems","Diamonds","Gold","Supplies","Exports","Creations","Designs"];
for (let i=1; i<=50; i++) {
    let id = 'SUP-' + (200 + i);
    let sname = randItem(lnames) + ' ' + randItem(supWords) + ' ' + String.fromCharCode(64+randInt(1,26));
    let contact = randItem(fnames);
    supplierIds.push(id);
    sql += "INSERT INTO SUPPLIER (SupplierId, SupplierName, ContactPerson, Phone, Email) VALUES ('" + id + "', '" + sname + "', '" + contact + "', '" + randPhone() + "', 'contact" + i + "@supplier.com');\n";
}

// 5. ITEM (50)
sql += "\n-- ITEM TABLE\n";
const itemIds = [];
const materials = ["Gold 22K", "Gold 18K", "Diamond", "Silver 925", "Platinum"];
for (let i=1; i<=50; i++) {
    let id = 'JW-' + (1000 + i);
    let catId = randItem(categoryIds);
    let supId = randItem(supplierIds);
    let mat = randItem(materials);
    let weight = (Math.random() * 40 + 2).toFixed(2);
    let price = randInt(5000, 500000);
    let stock = randInt(5, 50);
    let name = mat + ' ' + catNames[i % catNames.length];
    itemIds.push({id, price});
    sql += "INSERT INTO ITEM (ItemId, ItemName, CategoryId, SupplierId, Material, Weight, BasePrice, CurrentStock, ReorderLevel) VALUES ('" + id + "', '" + name + "', '" + catId + "', '" + supId + "', '" + mat + "', " + weight + ", " + price + ", " + stock + ", 5);\n";
}

// 6 & 7. BILL and BILL_ITEM (50)
sql += "\n-- BILL & BILL_ITEM TABLES\n";
const billIds = [];
for (let i=1; i<=50; i++) {
    let id = 'BL-' + (3000 + i);
    billIds.push(id);
    let cid = randItem(customerIds);
    let eid = randItem(employeeIds);
    let methods = ["Card", "UPI", "Cash", "Bank Transfer"];
    let method = randItem(methods);
    
    let numItems = randInt(1, 4);
    let billItems = [];
    let subtotal = 0;
    for(let j=0; j<numItems; j++) {
        let itm = randItem(itemIds);
        let qty = randInt(1, 3);
        subtotal += (itm.price * qty);
        billItems.push({id: itm.id, qty, price: itm.price});
    }
    
    let tax = Math.round(subtotal * 0.03);
    let discount = Math.round(subtotal * (randInt(0,10)/100));
    let total = subtotal + tax - discount;
    let daysAgo = randInt(1, 50);
    
    sql += "INSERT INTO BILL (BillId, CustomerId, EmployeeId, BillDate, TotalAmount, DiscountAmount, TaxAmount, PaymentMethod) VALUES ('" + id + "', '" + cid + "', '" + eid + "', CURRENT_TIMESTAMP - INTERVAL '" + daysAgo + "' DAY, " + total + ", " + discount + ", " + tax + ", '" + method + "');\n";
    
    for(let bi of billItems) {
        sql += "INSERT INTO BILL_ITEM (BillId, ItemId, Quantity, UnitPrice) VALUES ('" + id + "', '" + bi.id + "', " + bi.qty + ", " + bi.price + ");\n";
    }
}

// 8 & 9. PURCHASE and PURCHASE_ITEM (50)
sql += "\n-- PURCHASE & PURCHASE_ITEM TABLES\n";
for (let i=1; i<=50; i++) {
    let id = 'PO-' + (1200 + i);
    let sid = randItem(supplierIds);
    let methods = ["Bank Transfer", "Cheque", "Credit"];
    let method = randItem(methods);
    
    let numItems = randInt(1, 5);
    let purItems = [];
    let total = 0;
    for(let j=0; j<numItems; j++) {
        let itm = randItem(itemIds);
        let qty = randInt(5, 20);
        let costPrice = Math.round(itm.price * 0.7);
        total += (costPrice * qty);
        purItems.push({id: itm.id, qty, costPrice});
    }
    
    let daysAgo = randInt(1, 50);
    
    sql += "INSERT INTO PURCHASE (PurchaseId, SupplierId, PurchaseDate, TotalAmount, Status, PaymentMethod) VALUES ('" + id + "', '" + sid + "', CURRENT_TIMESTAMP - INTERVAL '" + daysAgo + "' DAY, " + total + ", 'Completed', '" + method + "');\n";
    
    for(let pi of purItems) {
        sql += "INSERT INTO PURCHASE_ITEM (PurchaseId, ItemId, Quantity, UnitCost) VALUES ('" + id + "', '" + pi.id + "', " + pi.qty + ", " + pi.costPrice + ");\n";
    }
}

sql += "\n-- ==========================================\n" +
"-- 4. VIEWS (Reports & Analytics)\n" +
"-- ==========================================\n\n" +
"CREATE OR REPLACE VIEW V_INVENTORY AS\n" +
"SELECT \n" +
"    i.ItemId,\n" +
"    i.ItemName,\n" +
"    c.CategoryName,\n" +
"    i.CurrentStock,\n" +
"    i.ReorderLevel,\n" +
"    i.BasePrice AS SellingPrice,\n" +
"    s.SupplierName,\n" +
"    (SELECT MAX(PurchaseDate) \n" +
"     FROM PURCHASE p \n" +
"     JOIN PURCHASE_ITEM pi ON p.PurchaseId = pi.PurchaseId \n" +
"     WHERE pi.ItemId = i.ItemId) AS LastRestockedDate\n" +
"FROM ITEM i\n" +
"JOIN CATEGORY c ON i.CategoryId = c.CategoryId\n" +
"JOIN SUPPLIER s ON i.SupplierId = s.SupplierId;\n\n" +
"CREATE OR REPLACE VIEW V_CUSTOMER_STATS AS\n" +
"SELECT \n" +
"    c.CustomerId,\n" +
"    c.CustomerName,\n" +
"    c.Phone,\n" +
"    COUNT(b.BillId) AS TotalBills,\n" +
"    NVL(SUM(b.TotalAmount), 0) AS TotalSpent,\n" +
"    MAX(b.BillDate) AS LastVisit\n" +
"FROM CUSTOMER c\n" +
"LEFT JOIN BILL b ON c.CustomerId = b.CustomerId\n" +
"GROUP BY \n" +
"    c.CustomerId, \n" +
"    c.CustomerName, \n" +
"    c.Phone;\n\n" +
"CREATE OR REPLACE VIEW V_REPORTS AS\n" +
"SELECT \n" +
"    TRUNC(b.BillDate) AS SaleDate,\n" +
"    COUNT(DISTINCT b.BillId) AS TotalOrders,\n" +
"    SUM(b.TotalAmount) AS DailyRevenue\n" +
"FROM BILL b\n" +
"GROUP BY TRUNC(b.BillDate);\n\n" +
"COMMIT;\n";

fs.writeFileSync(fileOut, sql);
console.log('Successfully generated ' + fileOut);
