-- ===========================================================
-- JewelTrack: Step 2 - Create Schema
-- Run as JEWELTRACK_APP user
-- Example: sqlplus JEWELTRACK_APP/JewelTrack@2024@localhost:1521/XEPDB1 @02_schema.sql
-- ===========================================================

-- Drop tables in reverse FK order (safe re-run)
BEGIN EXECUTE IMMEDIATE 'DROP TABLE BILL_ITEM CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PURCHASE_ITEM CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE BILL CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PURCHASE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ITEM CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CATEGORY CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE SUPPLIER CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE EMPLOYEE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CUSTOMER CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- ============================================================
-- CUSTOMER
-- ============================================================
CREATE TABLE CUSTOMER (
  CUSTOMERID   VARCHAR2(20)  NOT NULL,
  CUSTOMERNAME VARCHAR2(100) NOT NULL,
  PHONE        VARCHAR2(20)  NOT NULL,
  CONSTRAINT PK_CUSTOMER PRIMARY KEY (CUSTOMERID)
);

-- ============================================================
-- EMPLOYEE
-- ============================================================
CREATE TABLE EMPLOYEE (
  EMPLOYEEID   VARCHAR2(20)  NOT NULL,
  EMPLOYEENAME VARCHAR2(100) NOT NULL,
  CONSTRAINT PK_EMPLOYEE PRIMARY KEY (EMPLOYEEID)
);

-- ============================================================
-- CATEGORY
-- ============================================================
CREATE TABLE CATEGORY (
  CATEGORYID   VARCHAR2(20)  NOT NULL,
  CATEGORYNAME VARCHAR2(100) NOT NULL,
  CONSTRAINT PK_CATEGORY PRIMARY KEY (CATEGORYID)
);

-- ============================================================
-- SUPPLIER
-- ============================================================
CREATE TABLE SUPPLIER (
  SUPPLIERID    VARCHAR2(20)  NOT NULL,
  SUPPLIERNAME  VARCHAR2(100) NOT NULL,
  SUPPLIERPHONE VARCHAR2(20)  NOT NULL,
  CONSTRAINT PK_SUPPLIER PRIMARY KEY (SUPPLIERID)
);

-- ============================================================
-- ITEM
-- ============================================================
CREATE TABLE ITEM (
  ITEMID            VARCHAR2(20)   NOT NULL,
  ITEMNAME          VARCHAR2(200)  NOT NULL,
  CATEGORYID        VARCHAR2(20)   NOT NULL,
  MATERIAL          VARCHAR2(50)   NOT NULL,
  WEIGHT            NUMBER(10, 2)  DEFAULT 0,
  PRICE             NUMBER(12, 2)  NOT NULL,
  AVAILABLEQUANTITY NUMBER(10, 0)  DEFAULT 0,
  CONSTRAINT PK_ITEM PRIMARY KEY (ITEMID),
  CONSTRAINT FK_ITEM_CATEGORY FOREIGN KEY (CATEGORYID)
    REFERENCES CATEGORY (CATEGORYID)
);

-- ============================================================
-- BILL
-- ============================================================
CREATE TABLE BILL (
  BILLNO     VARCHAR2(20) NOT NULL,
  BILLDATE   DATE         NOT NULL,
  CUSTOMERID VARCHAR2(20) NOT NULL,
  EMPLOYEEID VARCHAR2(20) NOT NULL,
  CONSTRAINT PK_BILL PRIMARY KEY (BILLNO),
  CONSTRAINT FK_BILL_CUSTOMER FOREIGN KEY (CUSTOMERID)
    REFERENCES CUSTOMER (CUSTOMERID),
  CONSTRAINT FK_BILL_EMPLOYEE FOREIGN KEY (EMPLOYEEID)
    REFERENCES EMPLOYEE (EMPLOYEEID)
);

-- ============================================================
-- BILL_ITEM
-- ============================================================
CREATE TABLE BILL_ITEM (
  BILLNO   VARCHAR2(20) NOT NULL,
  ITEMID   VARCHAR2(20) NOT NULL,
  QUANTITY NUMBER(10, 0) NOT NULL,
  CONSTRAINT PK_BILL_ITEM PRIMARY KEY (BILLNO, ITEMID),
  CONSTRAINT FK_BILLITEM_BILL FOREIGN KEY (BILLNO)
    REFERENCES BILL (BILLNO),
  CONSTRAINT FK_BILLITEM_ITEM FOREIGN KEY (ITEMID)
    REFERENCES ITEM (ITEMID)
);

-- ============================================================
-- PURCHASE
-- ============================================================
CREATE TABLE PURCHASE (
  PURCHASEID   VARCHAR2(20) NOT NULL,
  PURCHASEDATE DATE         NOT NULL,
  SUPPLIERID   VARCHAR2(20) NOT NULL,
  CONSTRAINT PK_PURCHASE PRIMARY KEY (PURCHASEID),
  CONSTRAINT FK_PURCHASE_SUPPLIER FOREIGN KEY (SUPPLIERID)
    REFERENCES SUPPLIER (SUPPLIERID)
);

-- ============================================================
-- PURCHASE_ITEM
-- ============================================================
CREATE TABLE PURCHASE_ITEM (
  PURCHASEID VARCHAR2(20)  NOT NULL,
  ITEMID     VARCHAR2(20)  NOT NULL,
  QUANTITY   NUMBER(10, 0) NOT NULL,
  COSTPRICE  NUMBER(12, 2) NOT NULL,
  CONSTRAINT PK_PURCHASE_ITEM PRIMARY KEY (PURCHASEID, ITEMID),
  CONSTRAINT FK_PURITEM_PURCHASE FOREIGN KEY (PURCHASEID)
    REFERENCES PURCHASE (PURCHASEID),
  CONSTRAINT FK_PURITEM_ITEM FOREIGN KEY (ITEMID)
    REFERENCES ITEM (ITEMID)
);

COMMIT;

PROMPT ============================================================
PROMPT  JewelTrack schema created: 9 tables with all PKs and FKs.
PROMPT ============================================================
