-- ===========================================================
-- JewelTrack: Step 4 - Helper Views for Reporting
-- Run as JEWELTRACK_APP user AFTER 03_seed.sql
-- These views do NOT alter the core schema.
-- ===========================================================

-- Drop views if they exist
BEGIN EXECUTE IMMEDIATE 'DROP VIEW V_CUSTOMER_STATS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW V_SUPPLIER_STATS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW V_INVENTORY'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW V_BILL_DETAIL'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW V_PURCHASE_DETAIL'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- ============================================================
-- V_CUSTOMER_STATS
-- Aggregates purchase count, total spend, last visit per customer.
-- Derives status: Preferred / Regular / Inactive
-- ============================================================
CREATE OR REPLACE VIEW V_CUSTOMER_STATS AS
SELECT
  C.CUSTOMERID,
  C.CUSTOMERNAME,
  C.PHONE,
  NVL(STATS.TOTALBILLS, 0)       AS TOTALPURCHASES,
  NVL(STATS.TOTALSPENT, 0)       AS TOTALSPENT,
  STATS.LASTVISIT,
  CASE
    WHEN NVL(STATS.TOTALSPENT, 0) >= 750000 OR NVL(STATS.TOTALBILLS, 0) >= 15 THEN 'Preferred'
    WHEN NVL(STATS.TOTALBILLS, 0) > 0
         AND (STATS.LASTVISIT IS NULL OR STATS.LASTVISIT >= SYSDATE - 60) THEN 'Regular'
    ELSE 'Inactive'
  END AS STATUS,
  TOP_CAT.CATEGORYNAME AS FAVORITECATEGORY
FROM CUSTOMER C
LEFT JOIN (
  SELECT
    B.CUSTOMERID,
    COUNT(DISTINCT B.BILLNO)                                   AS TOTALBILLS,
    SUM(BI.QUANTITY * I.PRICE)                                 AS TOTALSPENT,
    MAX(B.BILLDATE)                                            AS LASTVISIT
  FROM BILL B
  JOIN BILL_ITEM BI ON B.BILLNO = BI.BILLNO
  JOIN ITEM I       ON BI.ITEMID = I.ITEMID
  GROUP BY B.CUSTOMERID
) STATS ON C.CUSTOMERID = STATS.CUSTOMERID
LEFT JOIN (
  -- Most purchased category per customer
  SELECT CUSTOMERID, CATEGORYNAME
  FROM (
    SELECT
      B.CUSTOMERID,
      CAT.CATEGORYNAME,
      SUM(BI.QUANTITY) AS QTY_SUM,
      RANK() OVER (PARTITION BY B.CUSTOMERID ORDER BY SUM(BI.QUANTITY) DESC) AS RNK
    FROM BILL B
    JOIN BILL_ITEM BI ON B.BILLNO  = BI.BILLNO
    JOIN ITEM I       ON BI.ITEMID = I.ITEMID
    JOIN CATEGORY CAT ON I.CATEGORYID = CAT.CATEGORYID
    GROUP BY B.CUSTOMERID, CAT.CATEGORYNAME
  )
  WHERE RNK = 1
) TOP_CAT ON C.CUSTOMERID = TOP_CAT.CUSTOMERID;

-- ============================================================
-- V_SUPPLIER_STATS
-- Aggregates order count, total purchase value, last supply date.
-- Derives status: Active (purchase in last 90 days) or Inactive
-- ============================================================
CREATE OR REPLACE VIEW V_SUPPLIER_STATS AS
SELECT
  S.SUPPLIERID,
  S.SUPPLIERNAME,
  S.SUPPLIERPHONE,
  NVL(STATS.TOTALORDERS, 0)  AS TOTALORDERS,
  NVL(STATS.TOTALVALUE, 0)   AS TOTALVALUE,
  STATS.LASTSUPPLY,
  CASE
    WHEN STATS.LASTSUPPLY IS NOT NULL AND STATS.LASTSUPPLY >= SYSDATE - 90 THEN 'Active'
    ELSE 'Inactive'
  END AS STATUS,
  TOP_CAT.CATEGORYNAME AS SUPPLYCATEGORY
FROM SUPPLIER S
LEFT JOIN (
  SELECT
    P.SUPPLIERID,
    COUNT(DISTINCT P.PURCHASEID)         AS TOTALORDERS,
    SUM(PI.QUANTITY * PI.COSTPRICE)      AS TOTALVALUE,
    MAX(P.PURCHASEDATE)                  AS LASTSUPPLY
  FROM PURCHASE P
  JOIN PURCHASE_ITEM PI ON P.PURCHASEID = PI.PURCHASEID
  GROUP BY P.SUPPLIERID
) STATS ON S.SUPPLIERID = STATS.SUPPLIERID
LEFT JOIN (
  SELECT SUPPLIERID, CATEGORYNAME
  FROM (
    SELECT
      P.SUPPLIERID,
      CAT.CATEGORYNAME,
      SUM(PI.QUANTITY) AS QTY_SUM,
      RANK() OVER (PARTITION BY P.SUPPLIERID ORDER BY SUM(PI.QUANTITY) DESC) AS RNK
    FROM PURCHASE P
    JOIN PURCHASE_ITEM PI ON P.PURCHASEID = PI.PURCHASEID
    JOIN ITEM I           ON PI.ITEMID    = I.ITEMID
    JOIN CATEGORY CAT     ON I.CATEGORYID = CAT.CATEGORYID
    GROUP BY P.SUPPLIERID, CAT.CATEGORYNAME
  )
  WHERE RNK = 1
) TOP_CAT ON S.SUPPLIERID = TOP_CAT.SUPPLIERID;

-- ============================================================
-- V_INVENTORY
-- Joins ITEM with CATEGORY; derives stock status
-- ============================================================
CREATE OR REPLACE VIEW V_INVENTORY AS
SELECT
  I.ITEMID,
  I.ITEMNAME,
  I.CATEGORYID,
  CAT.CATEGORYNAME,
  I.MATERIAL,
  I.WEIGHT,
  I.PRICE,
  I.AVAILABLEQUANTITY,
  CASE
    WHEN I.AVAILABLEQUANTITY = 0     THEN 'Out of Stock'
    WHEN I.AVAILABLEQUANTITY <= 5    THEN 'Low Stock'
    ELSE 'In Stock'
  END AS STOCKSTATUS,
  -- Most recent supplier for this item via latest purchase
  (SELECT S.SUPPLIERNAME
   FROM SUPPLIER S
   JOIN PURCHASE P   ON S.SUPPLIERID  = P.SUPPLIERID
   JOIN PURCHASE_ITEM PI ON P.PURCHASEID = PI.PURCHASEID
   WHERE PI.ITEMID = I.ITEMID
   AND ROWNUM = 1
   ORDER BY P.PURCHASEDATE DESC
  ) AS RECENTSUPPLIER
FROM ITEM I
JOIN CATEGORY CAT ON I.CATEGORYID = CAT.CATEGORYID;

-- ============================================================
-- V_BILL_DETAIL
-- Flattens BILL + BILL_ITEM + ITEM + CUSTOMER + EMPLOYEE for reporting
-- ============================================================
CREATE OR REPLACE VIEW V_BILL_DETAIL AS
SELECT
  B.BILLNO,
  B.BILLDATE,
  C.CUSTOMERID,
  C.CUSTOMERNAME,
  E.EMPLOYEEID,
  E.EMPLOYEENAME,
  BI.ITEMID,
  I.ITEMNAME,
  CAT.CATEGORYNAME,
  BI.QUANTITY,
  I.PRICE         AS UNITPRICE,
  BI.QUANTITY * I.PRICE AS LINEAMOUNT
FROM BILL      B
JOIN CUSTOMER  C   ON B.CUSTOMERID = C.CUSTOMERID
JOIN EMPLOYEE  E   ON B.EMPLOYEEID = E.EMPLOYEEID
JOIN BILL_ITEM BI  ON B.BILLNO     = BI.BILLNO
JOIN ITEM      I   ON BI.ITEMID    = I.ITEMID
JOIN CATEGORY  CAT ON I.CATEGORYID = CAT.CATEGORYID;

-- ============================================================
-- V_PURCHASE_DETAIL
-- Flattens PURCHASE + PURCHASE_ITEM + ITEM + SUPPLIER
-- ============================================================
CREATE OR REPLACE VIEW V_PURCHASE_DETAIL AS
SELECT
  P.PURCHASEID,
  P.PURCHASEDATE,
  S.SUPPLIERID,
  S.SUPPLIERNAME,
  PI.ITEMID,
  I.ITEMNAME,
  CAT.CATEGORYNAME,
  PI.QUANTITY,
  PI.COSTPRICE,
  PI.QUANTITY * PI.COSTPRICE AS LINEAMOUNT
FROM PURCHASE      P
JOIN SUPPLIER      S   ON P.SUPPLIERID  = S.SUPPLIERID
JOIN PURCHASE_ITEM PI  ON P.PURCHASEID  = PI.PURCHASEID
JOIN ITEM          I   ON PI.ITEMID     = I.ITEMID
JOIN CATEGORY      CAT ON I.CATEGORYID  = CAT.CATEGORYID;

COMMIT;

PROMPT ============================================================
PROMPT  Helper views created:
PROMPT   V_CUSTOMER_STATS, V_SUPPLIER_STATS, V_INVENTORY,
PROMPT   V_BILL_DETAIL, V_PURCHASE_DETAIL
PROMPT ============================================================
